<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->delete();
        $countries = array(
            array('id' => 1,'code' => 'AF' ,'name' => "Afghanistan",'phone' => 93),
            array('id' => 2,'code' => 'AL' ,'name' => "Albania",'phone' => 355),
            array('id' => 3,'code' => 'DZ' ,'name' => "Algeria",'phone' => 213),
            array('id' => 4,'code' => 'AS' ,'name' => "American Samoa",'phone' => 1684),
            array('id' => 5,'code' => 'AD' ,'name' => "Andorra",'phone' => 376),
            array('id' => 6,'code' => 'AO' ,'name' => "Angola",'phone' => 244),
            array('id' => 7,'code' => 'AI' ,'name' => "Anguilla",'phone' => 1264),
            array('id' => 8,'code' => 'AQ' ,'name' => "Antarctica",'phone' => 0),
            array('id' => 9,'code' => 'AG' ,'name' => "Antigua And Barbuda",'phone' => 1268),
            array('id' => 10,'code' => 'AR','name' => "Argentina",'phone' => 54),
            array('id' => 11,'code' => 'AM','name' => "Armenia",'phone' => 374),
            array('id' => 12,'code' => 'AW','name' => "Aruba",'phone' => 297),
            array('id' => 13,'code' => 'AU','name' => "Australia",'phone' => 61),
            array('id' => 14,'code' => 'AT','name' => "Austria",'phone' => 43),
            array('id' => 15,'code' => 'AZ','name' => "Azerbaijan",'phone' => 994),
            array('id' => 16,'code' => 'BS','name' => "Bahamas The",'phone' => 1242),
            array('id' => 17,'code' => 'BH','name' => "Bahrain",'phone' => 973),
            array('id' => 18,'code' => 'BD','name' => "Bangladesh",'phone' => 880),
            array('id' => 19,'code' => 'BB','name' => "Barbados",'phone' => 1246),
            array('id' => 20,'code' => 'BY','name' => "Belarus",'phone' => 375),
            array('id' => 21,'code' => 'BE','name' => "Belgium",'phone' => 32),
            array('id' => 22,'code' => 'BZ','name' => "Belize",'phone' => 501),
            array('id' => 23,'code' => 'BJ','name' => "Benin",'phone' => 229),
            array('id' => 24,'code' => 'BM','name' => "Bermuda",'phone' => 1441),
            array('id' => 25,'code' => 'BT','name' => "Bhutan",'phone' => 975),
            array('id' => 26,'code' => 'BO','name' => "Bolivia",'phone' => 591),
            array('id' => 27,'code' => 'BA','name' => "Bosnia and Herzegovina",'phone' => 387),
            array('id' => 28,'code' => 'BW','name' => "Botswana",'phone' => 267),
            array('id' => 29,'code' => 'BV','name' => "Bouvet Island",'phone' => 0),
            array('id' => 30,'code' => 'BR','name' => "Brazil",'phone' => 55),
            array('id' => 31,'code' => 'IO','name' => "British Indian Ocean Territory",'phone' => 246),
            array('id' => 32,'code' => 'BN','name' => "Brunei",'phone' => 673),
            array('id' => 33,'code' => 'BG','name' => "Bulgaria",'phone' => 359),
            array('id' => 34,'code' => 'BF','name' => "Burkina Faso",'phone' => 226),
            array('id' => 35,'code' => 'BI','name' => "Burundi",'phone' => 257),
            array('id' => 36,'code' => 'KH','name' => "Cambodia",'phone' => 855),
            array('id' => 37,'code' => 'CM','name' => "Cameroon",'phone' => 237),
            array('id' => 38,'code' => 'CA','name' => "Canada",'phone' => 1),
            array('id' => 39,'code' => 'CV','name' => "Cape Verde",'phone' => 238),
            array('id' => 40,'code' => 'KY','name' => "Cayman Islands",'phone' => 1345),
            array('id' => 41,'code' => 'CF','name' => "Central African Republic",'phone' => 236),
            array('id' => 42,'code' => 'TD','name' => "Chad",'phone' => 235),
            array('id' => 43,'code' => 'CL','name' => "Chile",'phone' => 56),
            array('id' => 44,'code' => 'CN','name' => "China",'phone' => 86),
            array('id' => 45,'code' => 'CX','name' => "Christmas Island",'phone' => 61),
            array('id' => 46,'code' => 'CC','name' => "Cocos (Keeling) Islands",'phone' => 672),
            array('id' => 47,'code' => 'CO','name' => "Colombia",'phone' => 57),
            array('id' => 48,'code' => 'KM','name' => "Comoros",'phone' => 269),
            array('id' => 49,'code' => 'CG','name' => "Congo",'phone' => 242),
            array('id' => 50,'code' => 'CD','name' => "Congo The Democratic Republic Of The",'phone' => 242),
            array('id' => 51,'code' => 'CK','name' => "Cook Islands",'phone' => 682),
            array('id' => 52,'code' => 'CR','name' => "Costa Rica",'phone' => 506),
            array('id' => 53,'code' => 'CI','name' => "Cote D Ivoire (Ivory Coast)",'phone' => 225),
            array('id' => 54,'code' => 'HR','name' => "Croatia (Hrvatska)",'phone' => 385),
            array('id' => 55,'code' => 'CU','name' => "Cuba",'phone' => 53),
            array('id' => 56,'code' => 'CY','name' => "Cyprus",'phone' => 357),
            array('id' => 57,'code' => 'CZ','name' => "Czech Republic",'phone' => 420),
            array('id' => 58,'code' => 'DK','name' => "Denmark",'phone' => 45),
            array('id' => 59,'code' => 'DJ','name' => "Djibouti",'phone' => 253),
            array('id' => 60,'code' => 'DM','name' => "Dominica",'phone' => 1767),
            array('id' => 61,'code' => 'DO','name' => "Dominican Republic",'phone' => 1809),
            array('id' => 62,'code' => 'TP','name' => "East Timor",'phone' => 670),
            array('id' => 63,'code' => 'EC','name' => "Ecuador",'phone' => 593),
            array('id' => 64,'code' => 'EG','name' => "Egypt",'phone' => 20),
            array('id' => 65,'code' => 'SV','name' => "El Salvador",'phone' => 503),
            array('id' => 66,'code' => 'GQ','name' => "Equatorial Guinea",'phone' => 240),
            array('id' => 67,'code' => 'ER','name' => "Eritrea",'phone' => 291),
            array('id' => 68,'code' => 'EE','name' => "Estonia",'phone' => 372),
            array('id' => 69,'code' => 'ET','name' => "Ethiopia",'phone' => 251),
            array('id' => 70,'code' => 'XA','name' => "External Territories of Australia",'phone' => 61),
            array('id' => 71,'code' => 'FK','name' => "Falkland Islands",'phone' => 500),
            array('id' => 72,'code' => 'FO','name' => "Faroe Islands",'phone' => 298),
            array('id' => 73,'code' => 'FJ','name' => "Fiji Islands",'phone' => 679),
            array('id' => 74,'code' => 'FI','name' => "Finland",'phone' => 358),
            array('id' => 75,'code' => 'FR','name' => "France",'phone' => 33),
            array('id' => 76,'code' => 'GF','name' => "French Guiana",'phone' => 594),
            array('id' => 77,'code' => 'PF','name' => "French Polynesia",'phone' => 689),
            array('id' => 78,'code' => 'TF','name' => "French Southern Territories",'phone' => 0),
            array('id' => 79,'code' => 'GA','name' => "Gabon",'phone' => 241),
            array('id' => 80,'code' => 'GM','name' => "Gambia The",'phone' => 220),
            array('id' => 81,'code' => 'GE','name' => "Georgia",'phone' => 995),
            array('id' => 82,'code' => 'DE','name' => "Germany",'phone' => 49),
            array('id' => 83,'code' => 'GH','name' => "Ghana",'phone' => 233),
            array('id' => 84,'code' => 'GI','name' => "Gibraltar",'phone' => 350),
            array('id' => 85,'code' => 'GR','name' => "Greece",'phone' => 30),
            array('id' => 86,'code' => 'GL','name' => "Greenland",'phone' => 299),
            array('id' => 87,'code' => 'GD','name' => "Grenada",'phone' => 1473),
            array('id' => 88,'code' => 'GP','name' => "Guadeloupe",'phone' => 590),
            array('id' => 89,'code' => 'GU','name' => "Guam",'phone' => 1671),
            array('id' => 90,'code' => 'GT','name' => "Guatemala",'phone' => 502),
            array('id' => 91,'code' => 'XU','name' => "Guernsey and Alderney",'phone' => 44),
            array('id' => 92,'code' => 'GN','name' => "Guinea",'phone' => 224),
            array('id' => 93,'code' => 'GW','name' => "Guinea-Bissau",'phone' => 245),
            array('id' => 94,'code' => 'GY','name' => "Guyana",'phone' => 592),
            array('id' => 95,'code' => 'HT','name' => "Haiti",'phone' => 509),
            array('id' => 96,'code' => 'HM','name' => "Heard and McDonald Islands",'phone' => 0),
            array('id' => 97,'code' => 'HN','name' => "Honduras",'phone' => 504),
            array('id' => 98,'code' => 'HK','name' => "Hong Kong S.A.R.",'phone' => 852),
            array('id' => 99,'code' => 'HU','name' => "Hungary",'phone' => 36),
            array('id' => 100,'code' => 'IS','name' => "Iceland",'phone' => 354),
            array('id' => 101,'code' => 'IN','name' => "India",'phone' => 91),
            array('id' => 102,'code' => 'ID','name' => "Indonesia",'phone' => 62),
            array('id' => 103,'code' => 'IR','name' => "Iran",'phone' => 98),
            array('id' => 104,'code' => 'IQ','name' => "Iraq",'phone' => 964),
            array('id' => 105,'code' => 'IE','name' => "Ireland",'phone' => 353),
            array('id' => 106,'code' => 'IL','name' => "Israel",'phone' => 972),
            array('id' => 107,'code' => 'IT','name' => "Italy",'phone' => 39),
            array('id' => 108,'code' => 'JM','name' => "Jamaica",'phone' => 1876),
            array('id' => 109,'code' => 'JP','name' => "Japan",'phone' => 81),
            array('id' => 110,'code' => 'XJ','name' => "Jersey",'phone' => 44),
            array('id' => 111,'code' => 'JO','name' => "Jordan",'phone' => 962),
            array('id' => 112,'code' => 'KZ','name' => "Kazakhstan",'phone' => 7),
            array('id' => 113,'code' => 'KE','name' => "Kenya",'phone' => 254),
            array('id' => 114,'code' => 'KI','name' => "Kiribati",'phone' => 686),
            array('id' => 115,'code' => 'KP','name' => "Korea North",'phone' => 850),
            array('id' => 116,'code' => 'KR','name' => "Korea South",'phone' => 82),
            array('id' => 117,'code' => 'KW','name' => "Kuwait",'phone' => 965),
            array('id' => 118,'code' => 'KG','name' => "Kyrgyzstan",'phone' => 996),
            array('id' => 119,'code' => 'LA','name' => "Laos",'phone' => 856),
            array('id' => 120,'code' => 'LV','name' => "Latvia",'phone' => 371),
            array('id' => 121,'code' => 'LB','name' => "Lebanon",'phone' => 961),
            array('id' => 122,'code' => 'LS','name' => "Lesotho",'phone' => 266),
            array('id' => 123,'code' => 'LR','name' => "Liberia",'phone' => 231),
            array('id' => 124,'code' => 'LY','name' => "Libya",'phone' => 218),
            array('id' => 125,'code' => 'LI','name' => "Liechtenstein",'phone' => 423),
            array('id' => 126,'code' => 'LT','name' => "Lithuania",'phone' => 370),
            array('id' => 127,'code' => 'LU','name' => "Luxembourg",'phone' => 352),
            array('id' => 128,'code' => 'MO','name' => "Macau S.A.R.",'phone' => 853),
            array('id' => 129,'code' => 'MK','name' => "Macedonia",'phone' => 389),
            array('id' => 130,'code' => 'MG','name' => "Madagascar",'phone' => 261),
            array('id' => 131,'code' => 'MW','name' => "Malawi",'phone' => 265),
            array('id' => 132,'code' => 'MY','name' => "Malaysia",'phone' => 60),
            array('id' => 133,'code' => 'MV','name' => "Maldives",'phone' => 960),
            array('id' => 134,'code' => 'ML','name' => "Mali",'phone' => 223),
            array('id' => 135,'code' => 'MT','name' => "Malta",'phone' => 356),
            array('id' => 136,'code' => 'XM','name' => "Man (Isle of)",'phone' => 44),
            array('id' => 137,'code' => 'MH','name' => "Marshall Islands",'phone' => 692),
            array('id' => 138,'code' => 'MQ','name' => "Martinique",'phone' => 596),
            array('id' => 139,'code' => 'MR','name' => "Mauritania",'phone' => 222),
            array('id' => 140,'code' => 'MU','name' => "Mauritius",'phone' => 230),
            array('id' => 141,'code' => 'YT','name' => "Mayotte",'phone' => 269),
            array('id' => 142,'code' => 'MX','name' => "Mexico",'phone' => 52),
            array('id' => 143,'code' => 'FM','name' => "Micronesia",'phone' => 691),
            array('id' => 144,'code' => 'MD','name' => "Moldova",'phone' => 373),
            array('id' => 145,'code' => 'MC','name' => "Monaco",'phone' => 377),
            array('id' => 146,'code' => 'MN','name' => "Mongolia",'phone' => 976),
            array('id' => 147,'code' => 'MS','name' => "Montserrat",'phone' => 1664),
            array('id' => 148,'code' => 'MA','name' => "Morocco",'phone' => 212),
            array('id' => 149,'code' => 'MZ','name' => "Mozambique",'phone' => 258),
            array('id' => 150,'code' => 'MM','name' => "Myanmar",'phone' => 95),
            array('id' => 151,'code' => 'NA','name' => "Namibia",'phone' => 264),
            array('id' => 152,'code' => 'NR','name' => "Nauru",'phone' => 674),
            array('id' => 153,'code' => 'NP','name' => "Nepal",'phone' => 977),
            array('id' => 154,'code' => 'AN','name' => "Netherlands Antilles",'phone' => 599),
            array('id' => 155,'code' => 'NL','name' => "Netherlands The",'phone' => 31),
            array('id' => 156,'code' => 'NC','name' => "New Caledonia",'phone' => 687),
            array('id' => 157,'code' => 'NZ','name' => "New Zealand",'phone' => 64),
            array('id' => 158,'code' => 'NI','name' => "Nicaragua",'phone' => 505),
            array('id' => 159,'code' => 'NE','name' => "Niger",'phone' => 227),
            array('id' => 160,'code' => 'NG','name' => "Nigeria",'phone' => 234),
            array('id' => 161,'code' => 'NU','name' => "Niue",'phone' => 683),
            array('id' => 162,'code' => 'NF','name' => "Norfolk Island",'phone' => 672),
            array('id' => 163,'code' => 'MP','name' => "Northern Mariana Islands",'phone' => 1670),
            array('id' => 164,'code' => 'NO','name' => "Norway",'phone' => 47),
            array('id' => 165,'code' => 'OM','name' => "Oman",'phone' => 968),
            array('id' => 166,'code' => 'PK','name' => "Pakistan",'phone' => 92),
            array('id' => 167,'code' => 'PW','name' => "Palau",'phone' => 680),
            array('id' => 168,'code' => 'PS','name' => "Palestinian Territory Occupied",'phone' => 970),
            array('id' => 169,'code' => 'PA','name' => "Panama",'phone' => 507),
            array('id' => 170,'code' => 'PG','name' => "Papua new Guinea",'phone' => 675),
            array('id' => 171,'code' => 'PY','name' => "Paraguay",'phone' => 595),
            array('id' => 172,'code' => 'PE','name' => "Peru",'phone' => 51),
            array('id' => 173,'code' => 'PH','name' => "Philippines",'phone' => 63),
            array('id' => 174,'code' => 'PN','name' => "Pitcairn Island",'phone' => 0),
            array('id' => 175,'code' => 'PL','name' => "Poland",'phone' => 48),
            array('id' => 176,'code' => 'PT','name' => "Portugal",'phone' => 351),
            array('id' => 177,'code' => 'PR','name' => "Puerto Rico",'phone' => 1787),
            array('id' => 178,'code' => 'QA','name' => "Qatar",'phone' => 974),
            array('id' => 179,'code' => 'RE','name' => "Reunion",'phone' => 262),
            array('id' => 180,'code' => 'RO','name' => "Romania",'phone' => 40),
            array('id' => 181,'code' => 'RU','name' => "Russia",'phone' => 70),
            array('id' => 182,'code' => 'RW','name' => "Rwanda",'phone' => 250),
            array('id' => 183,'code' => 'SH','name' => "Saint Helena",'phone' => 290),
            array('id' => 184,'code' => 'KN','name' => "Saint Kitts And Nevis",'phone' => 1869),
            array('id' => 185,'code' => 'LC','name' => "Saint Lucia",'phone' => 1758),
            array('id' => 186,'code' => 'PM','name' => "Saint Pierre and Miquelon",'phone' => 508),
            array('id' => 187,'code' => 'VC','name' => "Saint Vincent And The Grenadines",'phone' => 1784),
            array('id' => 188,'code' => 'WS','name' => "Samoa",'phone' => 684),
            array('id' => 189,'code' => 'SM','name' => "San Marino",'phone' => 378),
            array('id' => 190,'code' => 'ST','name' => "Sao Tome and Principe",'phone' => 239),
            array('id' => 191,'code' => 'SA','name' => "Saudi Arabia",'phone' => 966),
            array('id' => 192,'code' => 'SN','name' => "Senegal",'phone' => 221),
            array('id' => 193,'code' => 'RS','name' => "Serbia",'phone' => 381),
            array('id' => 194,'code' => 'SC','name' => "Seychelles",'phone' => 248),
            array('id' => 195,'code' => 'SL','name' => "Sierra Leone",'phone' => 232),
            array('id' => 196,'code' => 'SG','name' => "Singapore",'phone' => 65),
            array('id' => 197,'code' => 'SK','name' => "Slovakia",'phone' => 421),
            array('id' => 198,'code' => 'SI','name' => "Slovenia",'phone' => 386),
            array('id' => 199,'code' => 'XG','name' => "Smaller Territories of the UK",'phone' => 44),
            array('id' => 200,'code' => 'SB','name' => "Solomon Islands",'phone' => 677),
            array('id' => 201,'code' => 'SO','name' => "Somalia",'phone' => 252),
            array('id' => 202,'code' => 'ZA','name' => "South Africa",'phone' => 27),
            array('id' => 203,'code' => 'GS','name' => "South Georgia",'phone' => 0),
            array('id' => 204,'code' => 'SS','name' => "South Sudan",'phone' => 211),
            array('id' => 205,'code' => 'ES','name' => "Spain",'phone' => 34),
            array('id' => 206,'code' => 'LK','name' => "Sri Lanka",'phone' => 94),
            array('id' => 207,'code' => 'SD','name' => "Sudan",'phone' => 249),
            array('id' => 208,'code' => 'SR','name' => "Suriname",'phone' => 597),
            array('id' => 209,'code' => 'SJ','name' => "Svalbard And Jan Mayen Islands",'phone' => 47),
            array('id' => 210,'code' => 'SZ','name' => "Swaziland",'phone' => 268),
            array('id' => 211,'code' => 'SE','name' => "Sweden",'phone' => 46),
            array('id' => 212,'code' => 'CH','name' => "Switzerland",'phone' => 41),
            array('id' => 213,'code' => 'SY','name' => "Syria",'phone' => 963),
            array('id' => 214,'code' => 'TW','name' => "Taiwan",'phone' => 886),
            array('id' => 215,'code' => 'TJ','name' => "Tajikistan",'phone' => 992),
            array('id' => 216,'code' => 'TZ','name' => "Tanzania",'phone' => 255),
            array('id' => 217,'code' => 'TH','name' => "Thailand",'phone' => 66),
            array('id' => 218,'code' => 'TG','name' => "Togo",'phone' => 228),
            array('id' => 219,'code' => 'TK','name' => "Tokelau",'phone' => 690),
            array('id' => 220,'code' => 'TO','name' => "Tonga",'phone' => 676),
            array('id' => 221,'code' => 'TT','name' => "Trinidad And Tobago",'phone' => 1868),
            array('id' => 222,'code' => 'TN','name' => "Tunisia",'phone' => 216),
            array('id' => 223,'code' => 'TR','name' => "Turkey",'phone' => 90),
            array('id' => 224,'code' => 'TM','name' => "Turkmenistan",'phone' => 7370),
            array('id' => 225,'code' => 'TC','name' => "Turks And Caicos Islands",'phone' => 1649),
            array('id' => 226,'code' => 'TV','name' => "Tuvalu",'phone' => 688),
            array('id' => 227,'code' => 'UG','name' => "Uganda",'phone' => 256),
            array('id' => 228,'code' => 'UA','name' => "Ukraine",'phone' => 380),
            array('id' => 229,'code' => 'AE','name' => "United Arab Emirates",'phone' => 971),
            array('id' => 230,'code' => 'GB','name' => "United Kingdom",'phone' => 44),
            array('id' => 231,'code' => 'US','name' => "United States",'phone' => 1),
            array('id' => 232,'code' => 'UM','name' => "United States Minor Outlying Islands",'phone' => 1),
            array('id' => 233,'code' => 'UY','name' => "Uruguay",'phone' => 598),
            array('id' => 234,'code' => 'UZ','name' => "Uzbekistan",'phone' => 998),
            array('id' => 235,'code' => 'VU','name' => "Vanuatu",'phone' => 678),
            array('id' => 236,'code' => 'VA','name' => "Vatican City State (Holy See)",'phone' => 39),
            array('id' => 237,'code' => 'VE','name' => "Venezuela",'phone' => 58),
            array('id' => 238,'code' => 'VN','name' => "Vietnam",'phone' => 84),
            array('id' => 239,'code' => 'VG','name' => "Virgin Islands (British)",'phone' => 1284),
            array('id' => 240,'code' => 'VI','name' => "Virgin Islands (US)",'phone' => 1340),
            array('id' => 241,'code' => 'WF','name' => "Wallis And Futuna Islands",'phone' => 681),
            array('id' => 242,'code' => 'EH','name' => "Western Sahara",'phone' => 212),
            array('id' => 243,'code' => 'YE','name' => "Yemen",'phone' => 967),
            array('id' => 244,'code' => 'YU','name' => "Yugoslavia",'phone' => 38),
            array('id' => 245,'code' => 'ZM','name' => "Zambia",'phone' => 260),
            array('id' => 246,'code' => 'ZW','name' => "Zimbabwe",'phone' => 263),
        );
        DB::table('countries')->insert($countries);
    }
}
